# Generated by Django 3.2.8 on 2022-05-07 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('time', models.TimeField(default=datetime.datetime(2022, 5, 7, 13, 56, 27, 801244))),
                ('text', models.TextField(max_length=148)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
