# Generated by Django 3.2.8 on 2022-05-08 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(default=datetime.datetime(2022, 5, 8, 14, 18, 10), max_length=30),
        ),
    ]
