# Generated by Django 3.2.8 on 2022-05-08 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(max_length=148),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(default=datetime.datetime(2022, 5, 8, 14, 24), max_length=30),
        ),
    ]
