# Generated by Django 4.0.4 on 2022-05-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
